import * as env from '@testenv/env';
import { posixJoin } from '@tools/misc';
import { replaceSepToPosix } from 'my-node-fp';

export default [
  {
    resolvedFilePath: posixJoin(env.exampleType04Path, 'BubbleCls.tsx'),
    resolvedDirPath: replaceSepToPosix(env.exampleType04Path),
    relativeFilePath: posixJoin('type04', 'BubbleCls.tsx'),
    depth: 1,
    starExported: true,
    defaultExport: undefined,
    namedExports: [{ identifier: 'BubbleCls' }],
  },
  {
    resolvedFilePath: posixJoin(env.exampleType04Path, 'ComparisonCls.tsx'),
    resolvedDirPath: replaceSepToPosix(env.exampleType04Path),
    relativeFilePath: posixJoin('type04', 'ComparisonCls.tsx'),
    depth: 1,
    starExported: true,
    defaultExport: undefined,
    namedExports: [{ identifier: 'ComparisonCls' }],
  },
  {
    resolvedFilePath: posixJoin(env.exampleType04Path, 'createTypeScriptIndex.d.ts'),
    resolvedDirPath: replaceSepToPosix(env.exampleType04Path),
    relativeFilePath: posixJoin('type04', 'createTypeScriptIndex.d.ts'),
    depth: 1,
    starExported: true,
    defaultExport: undefined,
    namedExports: [
      { identifier: 'indexWriter' },
      { identifier: 'createTypeScriptIndex' },
      { identifier: 'ICreateTsIndexOption' },
    ],
  },
  {
    resolvedFilePath: posixJoin(env.exampleType04Path, 'HandsomelyCls.tsx'),
    resolvedDirPath: replaceSepToPosix(env.exampleType04Path),
    relativeFilePath: posixJoin('type04', 'HandsomelyCls.tsx'),
    depth: 1,
    starExported: true,
    defaultExport: undefined,
    namedExports: [{ identifier: 'HandsomelyCls' }],
  },
  {
    resolvedFilePath: posixJoin(env.exampleType04Path, 'index.tsx'),
    resolvedDirPath: replaceSepToPosix(env.exampleType04Path),
    relativeFilePath: posixJoin('type04', 'index.tsx'),
    depth: 1,
    starExported: true,
    defaultExport: { identifier: 'ReactApplication' },
    namedExports: [{ identifier: 'hello' }],
  },
  {
    resolvedFilePath: posixJoin(env.exampleType04Path, 'SampleCls.tsx'),
    resolvedDirPath: replaceSepToPosix(env.exampleType04Path),
    relativeFilePath: posixJoin('type04', 'SampleCls.tsx'),
    depth: 1,
    starExported: true,
    defaultExport: undefined,
    namedExports: [{ identifier: 'SampleCls' }],
  },
  {
    resolvedFilePath: posixJoin(env.exampleType04Path, 'SampleEnum.ts'),
    resolvedDirPath: replaceSepToPosix(env.exampleType04Path),
    relativeFilePath: posixJoin('type04', 'SampleEnum.ts'),
    depth: 1,
    starExported: true,
    defaultExport: { identifier: 'JobType' },
    namedExports: [{ identifier: 'GreetingMessage' }, { identifier: 'AddressType' }],
  },
  {
    resolvedFilePath: posixJoin(env.exampleType04Path, 'wellmade', 'ChildlikeCls.ts'),
    resolvedDirPath: posixJoin(env.exampleType04Path, 'wellmade'),
    relativeFilePath: posixJoin('type04', 'wellmade', 'ChildlikeCls.ts'),
    depth: 2,
    starExported: true,
    defaultExport: undefined,
    namedExports: [{ identifier: 'ChildlikeCls' }],
  },
  {
    resolvedFilePath: posixJoin(env.exampleType04Path, 'wellmade', 'carpenter', 'DiscussionCls.ts'),
    resolvedDirPath: posixJoin(env.exampleType04Path, 'wellmade', 'carpenter'),
    relativeFilePath: posixJoin('type04', 'wellmade', 'carpenter', 'DiscussionCls.ts'),
    depth: 3,
    starExported: true,
    defaultExport: undefined,
    namedExports: [{ identifier: 'DiscussionCls' }],
  },
  {
    resolvedFilePath: posixJoin(env.exampleType04Path, 'wellmade', 'carpenter', 'MakeshiftCls.ts'),
    resolvedDirPath: posixJoin(env.exampleType04Path, 'wellmade', 'carpenter'),
    relativeFilePath: posixJoin('type04', 'wellmade', 'carpenter', 'MakeshiftCls.ts'),
    depth: 3,
    starExported: true,
    defaultExport: undefined,
    namedExports: [{ identifier: 'MakeshiftCls' }],
  },
];
