import * as env from '#/testenv/env';
import { posixJoin } from '#/tools/misc';
import { replaceSepToPosix } from 'my-node-fp';

export default [
  {
    resolvedFilePath: posixJoin(env.exampleType04Path, 'BubbleCls.tsx'),
    resolvedDirPath: replaceSepToPosix(env.exampleType04Path),
    relativeFilePath: posixJoin('BubbleCls.tsx'),
    depth: 0,
    isEmpty: false,
    starExported: true,
    defaultExport: undefined,
    namedExports: [{ identifier: 'BubbleCls', isIsolatedModules: false }],
  },
  {
    resolvedFilePath: posixJoin(env.exampleType04Path, 'ComparisonCls.tsx'),
    resolvedDirPath: replaceSepToPosix(env.exampleType04Path),
    relativeFilePath: posixJoin('ComparisonCls.tsx'),
    depth: 0,
    isEmpty: false,
    starExported: true,
    defaultExport: undefined,
    namedExports: [{ identifier: 'ComparisonCls', isIsolatedModules: false }],
  },
  {
    resolvedFilePath: posixJoin(env.exampleType04Path, 'createTypeScriptIndex.d.ts'),
    resolvedDirPath: replaceSepToPosix(env.exampleType04Path),
    relativeFilePath: posixJoin('createTypeScriptIndex.d.ts'),
    depth: 0,
    isEmpty: false,
    starExported: true,
    defaultExport: undefined,
    namedExports: [
      { identifier: 'indexWriter', isIsolatedModules: false },
      { identifier: 'createTypeScriptIndex', isIsolatedModules: false },
      { identifier: 'ICreateTsIndexOption', isIsolatedModules: true },
    ],
  },
  {
    resolvedFilePath: posixJoin(env.exampleType04Path, 'HandsomelyCls.tsx'),
    resolvedDirPath: replaceSepToPosix(env.exampleType04Path),
    relativeFilePath: posixJoin('HandsomelyCls.tsx'),
    depth: 0,
    isEmpty: false,
    starExported: true,
    defaultExport: undefined,
    namedExports: [{ identifier: 'HandsomelyCls', isIsolatedModules: false }],
  },
  {
    resolvedFilePath: posixJoin(env.exampleType04Path, 'index.tsx'),
    resolvedDirPath: replaceSepToPosix(env.exampleType04Path),
    relativeFilePath: posixJoin('index.tsx'),
    depth: 0,
    isEmpty: false,
    starExported: true,
    defaultExport: { identifier: 'ReactApplication', isIsolatedModules: false },
    namedExports: [{ identifier: 'hello', isIsolatedModules: false }],
  },
  {
    resolvedFilePath: posixJoin(env.exampleType04Path, 'SampleCls.tsx'),
    resolvedDirPath: replaceSepToPosix(env.exampleType04Path),
    relativeFilePath: posixJoin('SampleCls.tsx'),
    depth: 0,
    isEmpty: false,
    starExported: true,
    defaultExport: undefined,
    namedExports: [{ identifier: 'SampleCls', isIsolatedModules: false }],
  },
  {
    resolvedFilePath: posixJoin(env.exampleType04Path, 'SampleEnum.ts'),
    resolvedDirPath: replaceSepToPosix(env.exampleType04Path),
    relativeFilePath: posixJoin('SampleEnum.ts'),
    depth: 0,
    isEmpty: false,
    starExported: true,
    defaultExport: { identifier: 'JobType', isIsolatedModules: false },
    namedExports: [
      { identifier: 'GreetingMessage', isIsolatedModules: false },
      { identifier: 'AddressType', isIsolatedModules: false },
    ],
  },
  {
    resolvedFilePath: posixJoin(env.exampleType04Path, 'wellmade', 'ChildlikeCls.ts'),
    resolvedDirPath: posixJoin(env.exampleType04Path, 'wellmade'),
    relativeFilePath: posixJoin('wellmade', 'ChildlikeCls.ts'),
    depth: 1,
    isEmpty: false,
    starExported: false,
    defaultExport: undefined,
    namedExports: [
      { identifier: 'ChildlikeCls', isIsolatedModules: false },
      { identifier: 'document', isIsolatedModules: false },
    ],
  },
  {
    resolvedFilePath: posixJoin(env.exampleType04Path, 'wellmade', 'carpenter', 'DiscussionCls.ts'),
    resolvedDirPath: posixJoin(env.exampleType04Path, 'wellmade', 'carpenter'),
    relativeFilePath: posixJoin('wellmade', 'carpenter', 'DiscussionCls.ts'),
    depth: 2,
    isEmpty: false,
    starExported: true,
    defaultExport: undefined,
    namedExports: [{ identifier: 'DiscussionCls', isIsolatedModules: false }],
  },
  {
    resolvedFilePath: posixJoin(env.exampleType04Path, 'wellmade', 'carpenter', 'MakeshiftCls.ts'),
    resolvedDirPath: posixJoin(env.exampleType04Path, 'wellmade', 'carpenter'),
    relativeFilePath: posixJoin('wellmade', 'carpenter', 'MakeshiftCls.ts'),
    depth: 2,
    isEmpty: false,
    starExported: true,
    defaultExport: undefined,
    namedExports: [{ identifier: 'MakeshiftCls', isIsolatedModules: false }],
  },
];
